<a href="https://colab.research.google.com/github/maglys/DAT801-Assignment1-/blob/main/dat801_assignment1_magnus_rev3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Kom i gang med DAT801-2021-konkurransen

***UNDER CONSTRUCTION***


Denne notebooken beskriver hvordan du kan:
1. Laste inn data: vi bruker Pandas til å laste inn trenings- og test-data
2. Undersøke features: vi undersøker et par features via statistikk og enkle plots.
3. Submitte dine prediksjoner for scoring (og plassering på leaderboard): etter at du har laget en modell og produsert prediksjoner på testdata så må du samle disse i en fil som Kaggle kan bruke til scoring. 

_Hvis du vil bruke denne notebooken som utgangspunkt for ditt eget arbeid kan du trykke "Fork"_

Du kan eventuelt bruke Google Colab eller din egen maskin. For å bruke Colab, (i) last ned notebooken på din egen maskin, (ii) gå til https://colab.research.google.com, logg inn, og last opp notebooken.

# Setup

In [1]:
%matplotlib inline
import numpy as np, pandas as pd, seaborn as sns, matplotlib.pyplot as plt
from pathlib import Path

# Last inn data

## Hvis du arbeider lokalt

Last ned data via Data-menyen på konkurransens hjemmeside.

## Hvis du bruker Colab

Kjør følgende celle:

In [2]:
train = pd.read_csv('https://raw.githubusercontent.com/alu042/DAT801/master/KaggleInClass/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/alu042/DAT801/master/KaggleInClass/test.csv')
sampleSubmission = pd.read_csv('https://raw.githubusercontent.com/alu042/DAT801/master/KaggleInClass/sample_submission.csv')

## Hvis du bruker Kaggle

In [3]:
#DATA = Path('../input/dat801-2021-assignment1')
#list(DATA.iterdir())

In [4]:
#train = pd.read_csv(DATA/'train.csv')
#test = pd.read_csv(DATA/'test.csv')
#sampleSubmission = pd.read_csv(DATA/'sample_submission.csv')

# Ta en titt på data

In [5]:
train = train.dropna()
train.head()

        id   f_0  f_1  f_2  f_3  f_4  ...  f_70  f_71  f_72  f_73  f_74  target
1    78028  16.0  0.0  1.0  1.0  6.0  ...   0.0   0.0   2.0   1.0   1.0       7
3    67966   0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0       1
11  101872   1.0  0.0  0.0  0.0  0.0  ...   0.0   2.0   2.0   0.0   0.0       7
12  165122   0.0  0.0  0.0  0.0  0.0  ...   1.0   1.0   0.0   0.0   0.0       8
17  110057   0.0  0.0  4.0  0.0  0.0  ...   0.0   0.0  13.0   0.0   0.0       5

[5 rows x 77 columns]

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61616 entries, 1 to 149997
Data columns (total 77 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      61616 non-null  int64
 1   f_0     61616 non-null  float64
 2   f_1     61616 non-null  float64
 3   f_2     61616 non-null  float64
 4   f_3     61616 non-null  float64
 5   f_4     61616 non-null  float64
 6   f_5     61616 non-null  float64
 7   f_6     61616 non-null  float64
 8   f_7     61616 non-null  float64
 9   f_8     61616 non-null  float64
 10  f_9     61616 non-null  float64
 11  f_10    61616 non-null  float64
 12  f_11    61616 non-null  float64
 13  f_12    61616 non-null  float64
 14  f_13    61616 non-null  float64
 15  f_14    61616 non-null  float64
 16  f_15    61616 non-null  float64
 17  f_16    61616 non-null  float64
 18  f_17    61616 non-null  float64
 19  f_18    61616 non-null  float64
 20  f_19    61616 non-null  float64
 21  f_20    61616 non-null  float64
 22  f_21    61616 non-null  float64
 23  f_22    61616 non-null  float64
 24  f_23    61616 non-null  float64
 25  f_24    61616 non-null  float64
 26  f_25    61616 non-null  float64
 27  f_26    61616 non-null  float64
 28  f_27    61616 non-null  float64
 29  f_28    61616 non-null  float64
 30  f_29    61616 non-null  float64
 31  f_30    61616 non-null  float64
 32  f_31    61616 non-null  float64
 33  f_32    61616 non-null  float64
 34  f_33    61616 non-null  float64
 35  f_34    61616 non-null  float64
 36  f_35    61616 non-null  float64
 37  f_36    61616 non-null  float64
 38  f_37    61616 non-null  float64
 39  f_38    61616 non-null  float64
 40  f_39    61616 non-null  float64
 41  f_40    61616 non-null  float64
 42  f_41    61616 non-null  float64
 43  f_42    61616 non-null  float64
 44  f_43    61616 non-null  float64
 45  f_44    61616 non-null  float64
 46  f_45    61616 non-null  float64
 47  f_46    61616 non-null  float64
 48  f_47    61616 non-null  float64
 49  f_48    61616 non-null  float64
 50  f_49    61616 non-null  float64
 51  f_50    61616 non-null  float64
 52  f_51    61616 non-null  float64
 53  f_52    61616 non-null  float64
 54  f_53    61616 non-null  float64
 55  f_54    61616 non-null  float64
 56  f_55    61616 non-null  float64
 57  f_56    61616 non-null  float64
 58  f_57    61616 non-null  float64
 59  f_58    61616 non-null  float64
 60  f_59    61616 non-null  float64
 61  f_60    61616 non-null  float64
 62  f_61    61616 non-null  float64
 63  f_62    61616 non-null  float64
 64  f_63    61616 non-null  float64
 65  f_64    61616 non-null  float64
 66  f_65    61616 non-null  float64
 67  f_66    61616 non-null  float64
 68  f_67    61616 non-null  float64
 69  f_68    61616 non-null  float64
 70  f_69    61616 non-null  float64
 71  f_70    61616 non-null  float64
 72  f_71    61616 non-null  float64
 73  f_72    61616 non-null  float64
 74  f_73    61616 non-null  float64
 75  f_74    61616 non-null  float64
 76  target  61616 non-null  int64
dtypes: float64(75), int64(2)
memory usage: 36.7 MB

Vi ser at det er 150.000 instanser i treningsdata. Det mangler noen verdier i hver av features (som er noe en må takle ved hjelp av imputering eller lignende).

In [7]:
test.head()

       id  f_0  f_1  f_2  f_3  f_4  ...  f_69  f_70  f_71  f_72  f_73  f_74
0  105982    0    0   10    0    0  ...     1     0     0     0     0     0
1  137351    0    0    0    0    0  ...     6     0     0     0     0     0
2  151824    0    0    0    0    0  ...     0     0     0     0     0     0
3  152873    1    2    0    1    2  ...     0     1     1     0     0     0
4   61900    3    0    0    0    0  ...     3     0     0     0     0     0

[5 rows x 76 columns]

In [8]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 76 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50000 non-null  int64
 1   f_0     50000 non-null  int64
 2   f_1     50000 non-null  int64
 3   f_2     50000 non-null  int64
 4   f_3     50000 non-null  int64
 5   f_4     50000 non-null  int64
 6   f_5     50000 non-null  int64
 7   f_6     50000 non-null  int64
 8   f_7     50000 non-null  int64
 9   f_8     50000 non-null  int64
 10  f_9     50000 non-null  int64
 11  f_10    50000 non-null  int64
 12  f_11    50000 non-null  int64
 13  f_12    50000 non-null  int64
 14  f_13    50000 non-null  int64
 15  f_14    50000 non-null  int64
 16  f_15    50000 non-null  int64
 17  f_16    50000 non-null  int64
 18  f_17    50000 non-null  int64
 19  f_18    50000 non-null  int64
 20  f_19    50000 non-null  int64
 21  f_20    50000 non-null  int64
 22  f_21    50000 non-null  int64
 23  f_22    50000 non-null  int64
 24  f_23    50000 non-null  int64
 25  f_24    50000 non-null  int64
 26  f_25    50000 non-null  int64
 27  f_26    50000 non-null  int64
 28  f_27    50000 non-null  int64
 29  f_28    50000 non-null  int64
 30  f_29    50000 non-null  int64
 31  f_30    50000 non-null  int64
 32  f_31    50000 non-null  int64
 33  f_32    50000 non-null  int64
 34  f_33    50000 non-null  int64
 35  f_34    50000 non-null  int64
 36  f_35    50000 non-null  int64
 37  f_36    50000 non-null  int64
 38  f_37    50000 non-null  int64
 39  f_38    50000 non-null  int64
 40  f_39    50000 non-null  int64
 41  f_40    50000 non-null  int64
 42  f_41    50000 non-null  int64
 43  f_42    50000 non-null  int64
 44  f_43    50000 non-null  int64
 45  f_44    50000 non-null  int64
 46  f_45    50000 non-null  int64
 47  f_46    50000 non-null  int64
 48  f_47    50000 non-null  int64
 49  f_48    50000 non-null  int64
 50  f_49    50000 non-null  int64
 51  f_50    50000 non-null  int64
 52  f_51    50000 non-null  int64
 53  f_52    50000 non-null  int64
 54  f_53    50000 non-null  int64
 55  f_54    50000 non-null  int64
 56  f_55    50000 non-null  int64
 57  f_56    50000 non-null  int64
 58  f_57    50000 non-null  int64
 59  f_58    50000 non-null  int64
 60  f_59    50000 non-null  int64
 61  f_60    50000 non-null  int64
 62  f_61    50000 non-null  int64
 63  f_62    50000 non-null  int64
 64  f_63    50000 non-null  int64
 65  f_64    50000 non-null  int64
 66  f_65    50000 non-null  int64
 67  f_66    50000 non-null  int64
 68  f_67    50000 non-null  int64
 69  f_68    50000 non-null  int64
 70  f_69    50000 non-null  int64
 71  f_70    50000 non-null  int64
 72  f_71    50000 non-null  int64
 73  f_72    50000 non-null  int64
 74  f_73    50000 non-null  int64
 75  f_74    50000 non-null  int64
dtypes: int64(76)
memory usage: 29.0 MB

Det er 50.000 test-instanser, og det ser ikke ut til å mangle noen features.

# Utforsk data, preprosesser data, utforsk modeller ("model selection"), prediker & evaluer

Jeg overlater disse delene til dere. Du bør utforske features via statistikk og plots, forsøke å avdekke sammenhenger mellom features og mellom features og labels ved å undersøke korrelasjoner og lignende, og gjerne forsøke å konstruere nye features ved å kombinere eksisterende. Før du kan trene modeller må du sørge for at data er på en egnet form. Du må blant annet finne ut hvordan du best kan takle manglende verdier ("missing values"). Husk å designe et grundig evalueringsoppsett som du kan bruke underveis i utforskingen av modeller. Kryss-validering er naturlig. Bør du kanskje vurdere stratifisert splitting i trening- og validerings-data? Hva med ensembling av flere modeller?

In [9]:
sampleSubmission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50000 non-null  int64
 1   target  50000 non-null  int64
dtypes: int64(2)
memory usage: 781.4 KB

#Setup

In [10]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
import scipy.sparse as sp
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import KNNImputer
from sklearn.metrics import confusion_matrix

#Splitt i trening og valideringsdata

## Splitt i X og y

Deler opp data i X (features) og y (target).

In [11]:
X = train.drop('target', axis=1)
X = X.drop('id', axis=1)
y = train['target']
X.head()

     f_0  f_1  f_2  f_3  f_4  f_5  ...  f_69  f_70  f_71  f_72  f_73  f_74
1   16.0  0.0  1.0  1.0  6.0  2.0  ...   0.0   0.0   0.0   2.0   1.0   1.0
3    0.0  0.0  0.0  0.0  0.0  1.0  ...   2.0   0.0   0.0   0.0   0.0   0.0
11   1.0  0.0  0.0  0.0  0.0  3.0  ...   0.0   0.0   2.0   2.0   0.0   0.0
12   0.0  0.0  0.0  0.0  0.0  1.0  ...   2.0   1.0   1.0   0.0   0.0   0.0
17   0.0  0.0  4.0  0.0  0.0  1.0  ...   1.0   0.0   0.0  13.0   0.0   0.0

[5 rows x 75 columns]

In [12]:
#y.head()
#X.shape
#type(y)
X.describe()
#X.info()

                f_0           f_1  ...          f_73          f_74
count  61616.000000  61616.000000  ...  61616.000000  61616.000000
mean       0.966518      1.163318  ...      2.962915      0.632320
std        3.886618      4.008660  ...     10.870784      3.912807
min        0.000000      0.000000  ...      0.000000      0.000000
25%        0.000000      0.000000  ...      0.000000      0.000000
50%        0.000000      0.000000  ...      0.000000      0.000000
75%        1.000000      1.000000  ...      1.000000      0.000000
max       61.000000     51.000000  ...    130.000000     52.000000

[8 rows x 75 columns]

In [13]:
# Split into training and test sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=42)

#Uforsk data

In [14]:
#pd.plotting.scatter_matrix(iris_df[features], c=iris_df['label'], figsize=(15,15), marker='o', s=60)
#plt.show()

##Feature selection

In [15]:
#Valg av egenskaper

In [16]:
import matplotlib.pyplot as plt
import seaborn as sb
# sb.heatmap(df.corr(), square=True, cmap='RdYlGn')

#Preprosessering

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

knn_pipe = Pipeline([('mms', MinMaxScaler()),
                     ('knn', KNeighborsClassifier())])

params = [{'knn__n_neighbors': [3, 5],
         'knn__weights': ['uniform', 'distance'],
         'knn__leaf_size': [15, 20]}]

gs_knn = GridSearchCV(knn_pipe,
                      param_grid=params,
                      scoring='accuracy',
                      cv=2)
         
gs_knn.fit(X_train, y_train)
gs_knn.best_params_

#Output:
#{'knn__leaf_size': 15, 'knn__n_neighbors': 5, 'knn__weights': 'distance'}

In [ ]:
gs_knn.best_params_

In [ ]:
# find best model score
gs_knn.score(X_train, y_train)

## Fylle inn manglende verdier

Univariate vs. Multivariate Imputation

### Dropp nullverdier

In [ ]:
# Gjort på toppen
# train = train.dropna() # dropper all data med NaN
train.shape

###SimpleImputer

In [ ]:

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(X_train)
SimpleImputer()
X_train = pd.DataFrame(imp.transform(X_train))
X_val = pd.DataFrame(imp.transform(X_val))

In [ ]:
X_train.describe()

### KNNImputer

In [ ]:
#nan = np.nan
#imputer = KNNImputer(n_neighbors=2, weights="uniform")
#imputer.fit_transform(train)

## Skaler data

In [ ]:
"""
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = StandardScaler()
#scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
"""

# Valg av ML-modell

## Random Forest

In [ ]:

# Import and train a machine learning model
rf = RandomForestClassifier(random_state=42, max_depth=10, n_estimators=300)
rf.fit(X_train, y_train)

## Kryssvalidering

In [ ]:
"""
cv_scores = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)

print(cv_scores)
print(cv_scores.mean())
"""

In [ ]:
y_val.head()
type(y_val) #pandas.core.series.Series
# print(y_val)

### Prediker & evaluer

In [ ]:
# Predict on the test data
y_pred = rf.predict(X_val)
#print(type(y_pred)) #numpy.ndarray
#y_test1=(y_test.to_numpy()) #Konvertering til numpy
#np.array(y_val)
# y = y.reshape(-1, 1)
# X = X.reshape(-1, 1)

# Evaluate the model
accuracy_score(y_val, y_pred)
"""for å legge til index
food= food.reset_index()
food= food.set_index('id')
print(food)
"""

### Confusion matrix

In [ ]:
# Print the confusion matrix
print(confusion_matrix(y_val, y_pred))
print()
"""
cv_scores_new = cross_val_score(sgd_clf, X_train_scale, y_train, cv=5, 
                            scoring='accuracy', n_jobs=-1)
print('Cross val score: ' + str(cv_scores_new))
print('CV score mean: ' + str(cv_scores_new.mean()))
"""
print()
print('Accuracy: ' + str(accuracy_score(y_val, y_pred)))

## SGDClassifier

In [ ]:

"""
# Evaluate the model
accuracy_score(y_test, y_pred)

cv_scores = cross_val_score(sgd_clf, X_train, y_train, cv=5, 
                            scoring='accuracy', n_jobs=-1)

# Create an instance of the StandardScaler
#scaler = StandardScaler()
scaler = MinMaxScaler()

# Using Scaler on the training data
scaler.fit(X_train)

# Transform the training and test data:
X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

# Create and train an SGDClassifier
sgd_clf_scale = SGDClassifier()
sgd_clf_scale.fit(X_train_scale, y_train)

# Compute the cross-validation predictions on the training set
y_test1, y_pred = cross_val_predict(sgd_clf, X_train_scale, y_train, cv=5)

"""

# Submission

Etter at du har trent din modell / dine modeller og produsert prediksjoner på test-data, så må du lage en CSV-fil på korrekt form som kan scores av Kaggle. Den skal ha samme form som `sample_submission.csv`:

In [ ]:
sampleSubmission.head()

Her er en fremgangsmåte:

Vi trenger først en vektor med tilfeldige prediksjoner:

In [ ]:
#target = np.random.choice(range(9), size=len(test))
#target

In [ ]:
test2 = test.drop('id', axis=1)
test.head()

In [ ]:
# Predict on the test data
target = rf.predict(test2)
target

Vi kan så bygge en dataframe via en Python dictionary med nøkler ("keys") 'id' og 'target':

In [ ]:
submission = pd.DataFrame({'id': test['id'], 'target': target})

In [ ]:
submission.head()

Denne kan lagres som en CSV vi kan laste opp på Kaggle for scoring:

In [ ]:
submission.to_csv('submission_mag1.csv', index=False)